"""add file_type to photo

Revision ID: 10778409e985
Revises: 1ef4fa68f554
Create Date: 2025-03-11 17:39:35.929532

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10778409e985"
down_revision = "1ef4fa68f554"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos",
        sa.Column("file_type", sa.String(), nullable=False, server_default="jpg"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "file_type")
    # ### end Alembic commands ###
