"""Description de la migration

Revision ID: 5b4eedc40dd0
Revises: 2cacd7f7033b
Create Date: 2025-02-04 14:46:15.082443

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b4eedc40dd0"
down_revision = "2cacd7f7033b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("otp_code", sa.String(length=6), nullable=True))
    op.add_column("users", sa.Column("otp_valid_until", sa.DateTime(), nullable=True))
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "otp_valid_until")
    op.drop_column("users", "otp_code")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
