"""Add description to Post model

Revision ID: 699cfcb5228a
Revises: 8c4aff14af4f
Create Date: 2025-02-12 11:12:54.095699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699cfcb5228a'
down_revision = '8c4aff14af4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
