"""Add description to Post model

Revision ID: 7c4193dadb7c
Revises: ddaab94a98ee
Create Date: 2025-02-21 09:58:19.858315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c4193dadb7c'
down_revision = 'ddaab94a98ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('name_on_s3', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'name_on_s3')
    # ### end Alembic commands ###
