"""Add description to Post model

Revision ID: 8e5014c2e57d
Revises: 699cfcb5228a
Create Date: 2025-02-12 12:19:51.970021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5014c2e57d'
down_revision = '699cfcb5228a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
