"""Add description to Post model

Revision ID: ae98495a3bb0
Revises: 8e5014c2e57d
Create Date: 2025-02-12 12:23:54.773201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae98495a3bb0'
down_revision = '8e5014c2e57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
