"""Add description to Post model

Revision ID: d85093bea70c
Revises: 7c4193dadb7c
Create Date: 2025-02-21 12:07:41.551772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85093bea70c'
down_revision = '7c4193dadb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
