"""Add Bookmark model and relationships

Revision ID: e0a489a0cf73
Revises: d85093bea70c
Create Date: 2025-02-26 14:09:12.312674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a489a0cf73'
down_revision = 'd85093bea70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
